apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cashinpostingcbsmta.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "cashinpostingcbsmta.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cashinpostingcbsmta.fullname" . }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
      labels:
        app: {{ include "cashinpostingcbsmta.fullname" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ include "cashinpostingcbsmta.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources: {{ toYaml .Values.resources | indent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
